### PR TITLE
[WIP] Bash fallback feature

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by danimesq** [comment]
If successfully worked and merged, this PR will solve the issue https://github.com/mitnk/cicada/issues/43.

**Comment by danimesq** [comment]
@mitnk, if you re-consider about supporting a Bash fallback, now you have a good base and incentive to start on.

Feel free to analyse the few lines GPT-4 has added, and how to fix it in order to work.

**Comment by mitnk** [comment]
Hey @danimesq Thanks for putting this in. I'm not sure I want to add this feature, as a counter-part to bash, cicada will not use bash as a fallback/dependency I would say.

And in current code of your PR, it will not work, if I run `ls file-doesnt-exist.txt`, it will return non-0 and I don't think we should run it again with bash, right?

I know [xonsh]https://xon.sh/) has fallbacks to other shells: use may have bad RC file, which would cause xonsh fail to bootup, in this case, it will exec to bash etc. But this is not the case in our context.

**Comment by mitnk** [comment]
cicada is itself functional for daily use. But I do use bash (for scripting things) - I would open a file `foo.sh` with following in it:
```
#!/bin/bash
bash scripting code ...
bash scripting code ...
...
```

And invoke it with `bash foo.sh`, `./foo.sh`, or just `foo.sh` if it's put in the PATH.

**Pull request closed without merging**
